### ISSUE TITLE
lots of exceptions

### ISSUE THREAD

**Issue by mkrumpholz** [mapstruct/mapstruct-idea#61]
`java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl cannot be cast to class com.intellij.psi.PsiAnnotationParameterList (com.intellij.psi.impl.source.tree.java.PsiNameValuePairImpl and com.intellij.psi.PsiAnnotationParameterList are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @311f48e6)
	at org.mapstruct.intellij.expression.JavaExpressionInjector.getLanguagesToInject(JavaExpressionInjector.java:68)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:423)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:345)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:164)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:321)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$getInjectedPsiFiles$3(InjectedGeneralHighlightingPass.java:184)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`

**Comment by filiphr** [comment]
Which version of the plugin are you using? I think that we fixed this error in the latest release.

Can you please share the mapper in which this exception is happening? Are you using `@Mappings` by any chance?

**Comment by mkrumpholz** [comment]
I didn't see the plugin update yet and therefore  looked only for open issues. 

As additional information for you, @filiphr : i'm (still) on IDEA 2020.1.4 and **NOT** using `@Mappings`. So if it really was fixed for  `@Mappings` only i expect that the Exception should be still there if i restart IDEA after the plugin update later.

**Comment by filiphr** [comment]
The fix was a bit more general and now we cast more safely. Please let us know once you try the update.

**Comment by mkrumpholz** [comment]
@filiphr OK, i used IDEA a bit after the restart and the exceptions seems to be gone now. :+1:
